name: Deploy to Azure App Service

env:
  AZURE_WEBAPP_NAME: padiscanner-analysis-api
  DOCKER_IMAGE_NAME: ghcr.io/fahminlb33/padiscanner.ml:latest

on:
  push:
    branches: [ "master" ]

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to GitHub container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}
        file: ./Dockerfile
    - name: Deploy to Azure Web App 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ env.DOCKER_IMAGE_NAME }}
